### ISSUE TITLE
facing issue while install app in site

### ISSUE THREAD

**Issue by mohsinalimat** [ParaLogicTech/textile#143]
Installing textile...
Updating DocTypes for textile       : [============                            ] 32%An error occurred while installing textile: Module import failed for Print Pricing Rule, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'convert_item_uom_for' from 'erpnext.stock.doctype.item.item' (/home/frappe/v14-bench/apps/erpnext/erpnext/stock/doctype/item/item.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 255, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/textile/textile/fabric_printing/doctype/print_pricing_rule/print_pricing_rule.py", line 7, in <module>
    from erpnext.stock.doctype.item.item import convert_item_uom_for
ImportError: cannot import name 'convert_item_uom_for' from 'erpnext.stock.doctype.item.item' (apps/erpnext/erpnext/stock/doctype/item/item.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 400, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 295, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 241, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 292, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1098, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 410, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 508, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 259, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Print Pricing Rule, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'convert_item_uom_for' from 'erpnext.stock.doctype.item.item' (apps/erpnext/erpnext/stock/doctype/item/item.py)

**Comment by mohsinalimat** [comment]
installing in version-14 latest

**Comment by SaiFi0102** [comment]
Hi Mohsin, check the README of this project: The app is in active development, and not released officially yet.

Note: This app only works on ParaLogic's fork of [Frappe](https://github.com/ParaLogicTech/frappe) and [ERPNext](https://github.com/ParaLogicTech/erpnext) and will not work on the official version of Frappe/ERPNext.
